server:
  shutdown: graceful
  port: 8080
  servlet:
    context-path: /

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tagsSorter: alpha
    operationsSorter: method

spring:
  application:
    name: mini-autorizador
  datasource:
    url: jdbc:mysql://localhost:3306/miniautorizador
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    url: jdbc:mysql://localhost:3306/miniautorizador
    user: root